### ISSUE TITLE
Missing Entities

### ISSUE THREAD

**Issue by PurelyAbrasive** [Crewski/njsPC-HA#51]
I am no longer getting all the entities.  I am not getting the status, current salt level or current output level.  They are all showing up when I go to the node webpage.  I have deleted and readded the integration and still only 9 entities are showing up.  My SWG is an Aquarite.

**Comment by PurelyAbrasive** [comment]
I uninstalled and reinstalled njsPC-HA again and when I add the new controller to it I get the following in the logs.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366
integration: Sensor (documentation, issues)
First occurred: 8:46:20 AM (1 occurrences)
Last logged: 8:46:20 AM

Error while setting up njspc_ha platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/njspc_ha/sensor.py", line 58, in async_setup_entry
    new_devices.append(PanelModeSensor(coordinator, config))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/njspc_ha/controller.py", line 109, in __init__
    self._value = data["mode"]["desc"]
                  ~~~~~~~~~~~~^^^^^^^^
KeyError: 'desc'

**Comment by sam2kb** [comment]
PanelModeSensor has been patched to avoid the KeyError when the controller’s mode object lacks a desc key. It now falls back in order: desc -> name -> val (string). That prior exception would have stopped the whole sensor platform from finishing setup—explaining why only a small subset of entities (and none of the chlorinator sensors) appeared.
